import { BookType } from "../../Types/book";
import img_1 from '../Images/525-5253539_3d-number-1-png.png'


export const booksList: BookType[] = [
  {
    id: "a886a250-c7c5-45f6-a529-95841483703e",
    title: "Honorable",
    author: "Shelley Northgraves",
    isbn: "900853588-2",
    publisher: "Leexo",
    publication_date: "1/15/1934",
    genre: "fiction",
    language: "Swedish",
    page_count: 486,
    price: 30.22,
    format: "paperback",
    rating: 2.1,
    description: "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    bestseller: true,
    series: "series",
    awards: "National Book Award",
    img: img_1,
    units: 10,
},
{
    id: "dcb1e749-8a42-414b-a828-eddaffd75e86",
    title: "Rev",
    author: "Gregoire Hegg",
    isbn: "627870497-8",
    publisher: "Kazio",
    publication_date: "1/17/1957",
    genre: "fiction",
    language: "Hiri Motu",
    page_count: 206,
    price: 7.98,
    format: "hardcover",
    rating: 3.9,
    description: "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    bestseller: false,
    series: "standalone",
    awards: "Booker Prize",
    img: img_1,
    units: 5,
},
{
    id: "014aeccb-2edc-4783-893e-b96d96b7a6db",
    title: "Dr",
    author: "Zilvia Dabel",
    isbn: "109780250-7",
    publisher: "Thoughtbridge",
    publication_date: "2/10/1992",
    genre: "fiction",
    language: "Khmer",
    page_count: 850,
    price: 8.21,
    format: "ebook",
    rating: 3.2,
    description: "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    bestseller: false,
    series: "standalone",
    awards: "Pulitzer Prize",
    img: img_1,
    units: 1,
},
{
    id: "2913fc04-e9af-4ef9-b594-8a978ca7d930",
    title: "Ms",
    author: "Terza Chaudhry",
    isbn: "528474402-0",
    publisher: "Thoughtworks",
    publication_date: "4/27/1931",
    genre: "romance",
    language: "Dutch",
    page_count: 959,
    price: 88.42,
    format: "paperback",
    rating: 2.7,
    description: "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    bestseller: false,
    series: "series",
    awards: "National Book Award",
    img: img_1,
    units: 0,
},
{
    id: "3075c6c7-cb97-43d9-b51c-8f043253d08c",
    title: "Rev",
    author: "Kin Trusse",
    isbn: "003910246-7",
    publisher: "Zooveo",
    publication_date: "1/16/2022",
    genre: "romance",
    language: "Punjabi",
    page_count: 449,
    price: 29.04,
    format: "ebook",
    rating: 3.5,
    description: "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    bestseller: true,
    series: "standalone",
    awards: "Pulitzer Prize",
    img: img_1,
    units: 10,
},
{
    id: "6bacb112-29b9-4fd4-8d3d-f46adf4706d9",
    title: "Honorable",
    author: "Barbara-anne Date",
    isbn: "605199016-X",
    publisher: "Fadeo",
    publication_date: "9/25/1952",
    genre: "romance",
    language: "Dari",
    page_count: 28,
    price: 69.4,
    format: "ebook",
    rating: 3.9,
    description: "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    bestseller: false,
    series: "standalone",
    awards: "Booker Prize",
    img: img_1,
    units: 3,
},
{
    id: "035d032e-b7f6-4ce8-8ebe-469a61beb0b2",
    title: "Mr",
    author: "Maressa Janse",
    isbn: "671145488-X",
    publisher: "Zoomdog",
    publication_date: "2/4/1901",
    genre: "non-fiction",
    language: "Ndebele",
    page_count: 728,
    price: 76.14,
    format: "paperback",
    rating: 1.3,
    description: "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    bestseller: true,
    series: "series",
    awards: "National Book Award",
    img: img_1,
    units: 7,
},
{
    id: "15cd28a0-9000-4452-ad01-6ff7578d508f",
    title: "Mr",
    author: "Husein Inskipp",
    isbn: "988011093-5",
    publisher: "Avamm",
    publication_date: "11/21/1987",
    genre: "romance",
    language: "Indonesian",
    page_count: 923,
    price: 79.0,
    format: "ebook",
    rating: 4.5,
    description: "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    bestseller: true,
    series: "standalone",
    awards: "National Book Award",
    img: img_1,
    units: 3,
},
{
    id: "3438e55e-ae67-46c4-84cd-92280a8233ee",
    title: "Honorable",
    author: "Gunther Diplock",
    isbn: "153613139-3",
    publisher: "Zoomzone",
    publication_date: "12/26/2020",
    genre: "romance",
    language: "Tamil",
    page_count: 344,
    price: 82.42,
    format: "hardcover",
    rating: 3.3,
    description: "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    bestseller: true,
    series: "series",
    awards: "National Book Award",
    img: img_1,
    units: 4,
},
{
    id: "5922e44e-ce7b-44b4-8b56-91e590762d85",
    title: "Mr",
    author: "Norma Heis",
    isbn: "986239653-9",
    publisher: "Cogibox",
    publication_date: "9/11/2022",
    genre: "non-fiction",
    language: "Malagasy",
    page_count: 78,
    price: 11.33,
    format: "hardcover",
    rating: 2.6,
    description: "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    bestseller: false,
    series: "series",
    awards: "Booker Prize",
    img: img_1,
    units: 10,
},
]


export default booksList;